<?php
/**
 * File: login.php
 * Author: Pan Zitao
 * Date: 2025-07-21
 * Description: Handles the server-side logic for user authentication.
 */

// --- Database connection information ---
$servername = "localhost:3307";
$db_username = "root";
$db_password = "123456";
$dbname = "lemon";

// --- Table and field information ---
$tableName = "users";
$usernameColumn = "username";
$passwordColumn = "password"; 

// Set the response header to JSON
header('Content-Type: application/json');

// Create database connection
$conn = new mysqli($servername, $db_username, $db_password, $dbname);

// Check connection
if ($conn->connect_error) {
    echo json_encode(['success' => false, 'message' => 'Database connection failed.']);
    exit();
}

// Get the JSON data from the frontend
$json_data = file_get_contents('php://input');
$data = json_decode($json_data);

// Check if data exists
if (!isset($data->username) || !isset($data->password)) {
    echo json_encode(['success' => false, 'message' => 'Invalid input.']);
    exit();
}

$username_from_user = $data->username;
$encrypted_password_from_user = $data->password;


// --- Database Query using Prepared Statements to prevent SQL Injection ---
// The '?' is a placeholder to avoid directly inserting user input into the query.
$stmt = $conn->prepare("SELECT $passwordColumn FROM $tableName WHERE $usernameColumn = ?");
$stmt->bind_param("s", $username_from_user);
// Execute the prepared statement on the database server.
$stmt->execute();
// Get the result set from the executed statement.
$result = $stmt->get_result();

if ($result->num_rows > 0) {
    $row = $result->fetch_assoc();
    $plain_password_from_db = $row[$passwordColumn];

    // Encrypt the plain password from the database using the Vigenère cipher
    // with the same key "lemon" to match the client-side encryption.
    $key = "lemon";
    $encrypted_password_from_db = "";
    for ($i = 0; $i < strlen($plain_password_from_db); $i++) {
        $pCharCode = ord($plain_password_from_db[$i]);
        $kChar = $key[$i % strlen($key)];
        $shift = ord(strtolower($kChar)) - ord('a'); // Get shift amount (0-25) from key

        $cCharCode;

        if ($pCharCode >= 97 && $pCharCode <= 122) { // a-z
            $cCharCode = (($pCharCode - 97 + $shift) % 26) + 97;
        } else if ($pCharCode >= 65 && $pCharCode <= 90) { // A-Z
            $cCharCode = (($pCharCode - 65 + $shift) % 26) + 65;
        } else if ($pCharCode >= 48 && $pCharCode <= 57) { // 0-9
            $cCharCode = (($pCharCode - 48 + $shift) % 10) + 48;
        } else {
            // For other characters, do not encrypt them.
            $cCharCode = $pCharCode;
        }
        $encrypted_password_from_db .= chr($cCharCode);
    }

    // Compare the encrypted password from the frontend with the one generated by the backend
    if ($encrypted_password_from_user === $encrypted_password_from_db) {
        
        // --- START: ADD THIS CODE ---
        // Login successful, start the session and store information
        session_start();
        
        // Store session data
        $_SESSION['loggedin'] = true;
        $_SESSION['username'] = $username_from_user;
        $_SESSION['login_time'] = time(); // Record the current Unix timestamp
        $_SESSION['last_activity'] = time(); // Record the last activity time for timeout check
        // --- END: ADD THIS CODE ---

        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['success' => false, 'message' => 'Incorrect password.']);
    }
} else {
    echo json_encode(['success' => false, 'message' => 'User not found.']);
}

$stmt->close();
$conn->close();

?>