<?php
// filepath: c:\Users\97701\Desktop\Lemon\lemon\login.php

// --- Database connection information ---
$servername = "localhost:3307";
$db_username = "root";
$db_password = "123456";
$dbname = "lemon";

// --- Table and field information ---
$tableName = "users";
$usernameColumn = "username";
$passwordColumn = "password"; 

// Set the response header to JSON
header('Content-Type: application/json');

// Create database connection
$conn = new mysqli($servername, $db_username, $db_password, $dbname);

// Check connection
if ($conn->connect_error) {
    echo json_encode(['success' => false, 'message' => 'Database connection failed.']);
    exit();
}

// Get the JSON data from the frontend
$json_data = file_get_contents('php://input');
$data = json_decode($json_data);

// Check if data exists
if (!isset($data->username) || !isset($data->password)) {
    echo json_encode(['success' => false, 'message' => 'Invalid input.']);
    exit();
}

$username_from_user = $data->username;
$encrypted_password_from_user = $data->password;


// --- Database Query using Prepared Statements to prevent SQL Injection ---
// The '?' is a placeholder to avoid directly inserting user input into the query.
$stmt = $conn->prepare("SELECT $passwordColumn FROM $tableName WHERE $usernameColumn = ?");
$stmt->bind_param("s", $username_from_user);
// Execute the prepared statement on the database server.
$stmt->execute();
// Get the result set from the executed statement.
$result = $stmt->get_result();

if ($result->num_rows > 0) {
    $row = $result->fetch_assoc();
    $plain_password_from_db = $row[$passwordColumn];

    // Encrypt the original password from the database on the server-side using the same Caesar cipher
    $shift = 3;
    $encrypted_password_from_db = "";
    for ($i = 0; $i < strlen($plain_password_from_db); $i++) {
        $charCode = ord($plain_password_from_db[$i]);
        if ($charCode >= 97 && $charCode <= 122) { // a-z
            $charCode = (($charCode - 97 + $shift) % 26) + 97;
        } else if ($charCode >= 65 && $charCode <= 90) { // A-Z
            $charCode = (($charCode - 65 + $shift) % 26) + 65;
        }
        $encrypted_password_from_db .= chr($charCode);
    }

    // Compare the encrypted password from the frontend with the one generated by the backend
    if ($encrypted_password_from_user === $encrypted_password_from_db) {
        
        // --- START: ADD THIS CODE ---
        // Login successful, start the session and store information
        session_start();
        
        // Store session data
        $_SESSION['loggedin'] = true;
        $_SESSION['username'] = $username_from_user;
        $_SESSION['login_time'] = time(); // Record the current Unix timestamp
        $_SESSION['last_activity'] = time(); // Record the last activity time for timeout check
        // --- END: ADD THIS CODE ---

        echo json_encode(['success' => true]);
    } else {
        echo json_encode(['success' => false, 'message' => 'Incorrect password.']);
    }
} else {
    echo json_encode(['success' => false, 'message' => 'User not found.']);
}

$stmt->close();
$conn->close();

?>